image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build-master:
  stage: build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker pull $CONTAINER_TEST_IMAGE || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --cache-from $CONTAINER_TEST_IMAGE -t $CONTAINER_TEST_IMAGE -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CONTAINER_TEST_IMAGE
    - docker push $CI_REGISTRY_IMAGE:latest

smoke-test:
  stage: test
  services:
    - postgres:9.6-alpine
  variables:
    DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    SECRET_KEY: test
  script:
    - docker run --rm -e SECRET_KEY=$SECRET_KEY -e DATABASE_URL=$DATABASE_URL -p 8000:8000 $CONTAINER_TEST_IMAGE
    - apk add --update --no-cache curl
    - curl -v -X GET "http://docker:8000"

deploy:
  stage: deploy
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $DOCKER_HUB_IMAGE
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
    - docker push $DOCKER_HUB_IMAGE
    - apk add --update --no-cache curl
    - curl -X GET "$WEBHOOK_URL"
  environment:
    name: production
    url: https://fakenewsdetector.augendre.info
  only:
    - master
