# Generated by Django 2.1.2 on 2018-10-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181005_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='scores_version',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
