# Generated by Django 2.1.3 on 2018-11-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181021_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='author_score',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='domain_score',
        ),
        migrations.AddField(
            model_name='webpage',
            name='base_domain',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webpage',
            name='content_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
