# Generated by Django 2.1.3 on 2018-11-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181110_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingRelatedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('web_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesting_related_articles', to='api.WebPage')),
            ],
        ),
    ]
