# Generated by Django 2.1.3 on 2018-11-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_interestingrelatedarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestingrelatedarticle',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
