# Generated by Django 2.1.3 on 2018-11-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181114_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='total_articles',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
