# Generated by Django 2.1.3 on 2018-12-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_webpage_total_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestingrelatedarticle',
            name='score',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
