# Generated by Django 2.1.4 on 2018-12-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_interestingrelatedarticle_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_domain', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='webpage',
            name='base_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_pages', to='api.BaseDomain'),
        ),
    ]
