# Generated by Django 2.1.4 on 2018-12-13 11:22
import tldextract
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    WebPage = apps.get_model('api', 'webpage')
    BaseDomain = apps.get_model('api', 'BaseDomain')
    db_alias = schema_editor.connection.alias

    tld_extract = tldextract.TLDExtract(
        cache_file='api/external_data/public_suffixes_list.dat',
        include_psl_private_domains=True
    )
    for article in WebPage.objects.using(db_alias).all():
        url_extraction = tld_extract(article.url)
        base_domain = f"{url_extraction.domain}.{url_extraction.suffix}".lower()
        domain, _ = BaseDomain.objects.get_or_create(base_domain=base_domain)
        article.base_domain = domain
        article.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_interestingrelatedarticle_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_domain', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='webpage',
            name='base_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_pages', to='api.BaseDomain'),
        ),
        migrations.RunPython(forwards),
    ]
