# Generated by Django 2.1.4 on 2018-12-13 11:44

from django.db import migrations, models
import django.db.models.deletion
import tldextract


def forwards(apps, schema_editor):
    InterestingRelatedArticle = apps.get_model('api', 'InterestingRelatedArticle')
    BaseDomain = apps.get_model('api', 'BaseDomain')
    db_alias = schema_editor.connection.alias

    tld_extract = tldextract.TLDExtract(
        cache_file='api/external_data/public_suffixes_list.dat',
        include_psl_private_domains=True
    )
    for article in InterestingRelatedArticle.objects.using(db_alias).all():
        url_extraction = tld_extract(article.url)
        base_domain = f"{url_extraction.domain}.{url_extraction.suffix}".lower()
        domain, _ = BaseDomain.objects.get_or_create(base_domain=base_domain)
        article.base_domain = domain
        article.save()


def backwards(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_auto_20181213_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedomain',
            name='isolated_articles_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='interestingrelatedarticle',
            name='base_domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='interesting_related_articles', to='api.BaseDomain'),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='interestingrelatedarticle',
            name='base_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='interesting_related_articles', to='api.BaseDomain'),
        )
    ]
