# Generated by Django 2.1.4 on 2018-12-13 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181213_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolatedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='basedomain',
            name='isolated_articles_count',
        ),
        migrations.AddField(
            model_name='isolatedarticle',
            name='base_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='isolated_articles', to='api.BaseDomain'),
        ),
    ]
